import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ChevronDown, ChevronUp } from "lucide-react";
import { getHrRecommendations } from "../../services/panelistWorkflowService";

const money = (value, currency) => value == null ? "Not recorded" : `${currency || ""} ${Number(value).toLocaleString(undefined, { minimumFractionDigits: 2 })}`;

export default function RecommendationsPage() {
  const [rows, setRows] = useState([]);
  const [open, setOpen] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { getHrRecommendations().then(setRows).catch((e) => setError(e.message)); }, []);
  return <div><p className="text-xs font-semibold uppercase text-emerald-600">Final review</p><h1 className="mt-3 text-3xl font-semibold">Panelist recommendations</h1><p className="mt-2 text-sm text-neutral-500">Review the applicant, job, interview scores, negotiated salary and panelist rationale before final offer approval.</p>
    {error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}
    <div className="mt-7 space-y-3">{rows.length === 0 && <p className="rounded-2xl bg-white p-5 text-neutral-500">No recommendations submitted yet.</p>}
      {rows.map((r) => { const expanded = open === r.id; return <article key={r.id} className="rounded-2xl border border-neutral-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold">{r.candidate}</h2><p className="text-sm text-neutral-500">{r.job} · {r.panelist}</p><p className="mt-1 text-xs text-neutral-400">{r.candidateEmail}{r.candidatePhone ? ` · ${r.candidatePhone}` : ""}</p></div><span className={`rounded-full px-3 py-1 text-xs font-semibold ${r.selected ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}>{r.selected ? "Recommended" : "Not recommended"}</span></div>
        <div className="mt-4 grid gap-3 rounded-xl bg-neutral-50 p-4 text-sm sm:grid-cols-3"><div><span className="text-neutral-400">Negotiated salary</span><p className="font-semibold">{money(r.desiredSalary, r.desiredSalaryCurrency)}</p></div><div><span className="text-neutral-400">Interview date</span><p className="font-semibold">{new Date(r.interviewedAt).toLocaleString()}</p></div><div><span className="text-neutral-400">Job arrangement</span><p className="font-semibold">{r.employmentType} · {r.workMode}</p></div></div>
        <p className="mt-4 whitespace-pre-wrap text-sm text-neutral-700"><span className="font-semibold">Panelist rationale:</span> {r.rationale}</p>
        <button onClick={() => setOpen(expanded ? null : r.id)} className="mt-4 inline-flex items-center gap-1 text-sm font-semibold text-emerald-700">{expanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />} {expanded ? "Hide details" : "Review full details"}</button>
        {expanded && <div className="mt-4 space-y-4 border-t border-neutral-100 pt-4 text-sm"><div className="grid gap-4 md:grid-cols-2"><section><h3 className="font-semibold">Applicant details</h3><p className="mt-2 text-neutral-600">{r.headline || "No headline"}{r.candidateLocation ? ` · ${r.candidateLocation}` : ""}</p>{r.bio && <p className="mt-2 whitespace-pre-wrap text-neutral-600">{r.bio}</p>}<div className="mt-2 flex flex-wrap gap-3 text-emerald-700">{r.linkedInUrl && <a href={r.linkedInUrl} target="_blank" rel="noreferrer">LinkedIn</a>}{r.gitHubUrl && <a href={r.gitHubUrl} target="_blank" rel="noreferrer">GitHub</a>}{r.portfolioUrl && <a href={r.portfolioUrl} target="_blank" rel="noreferrer">Portfolio</a>}</div>{r.skills?.length > 0 && <p className="mt-3 text-neutral-600">Skills: {r.skills.map((s) => `${s.name} (${s.proficiencyLevel}/5)`).join(", ")}</p>}</section><section><h3 className="font-semibold">Job details</h3><p className="mt-2 text-neutral-600">{r.jobLocation} · {r.employmentType} · {r.workMode}</p>{r.jobDescription && <p className="mt-2 whitespace-pre-wrap text-neutral-600">{r.jobDescription}</p>}<p className="mt-2 whitespace-pre-wrap text-neutral-600"><span className="font-medium">Requirements:</span> {r.requirements}</p></section></div><section><h3 className="font-semibold">Interview evaluation</h3><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Technical", r.technicalSkills], ["Problem solving", r.problemSolving], ["Communication", r.communication], ["Culture fit", r.cultureFit]].map(([label, value]) => <div key={label} className="rounded-lg bg-neutral-50 p-3"><span className="text-neutral-400">{label}</span><p className="font-semibold">{value ?? "–"}/5</p></div>)}</div>{r.interviewComments && <p className="mt-3 whitespace-pre-wrap text-neutral-600">{r.interviewComments}</p>}</section></div>}
        <div className="mt-4 flex items-center justify-between"><p className="text-xs text-neutral-400">Submitted {new Date(r.submittedAt).toLocaleString()}</p>{r.selected && <Link to="/hr/offers" className="text-sm font-semibold text-emerald-700">Review offer approvals →</Link>}</div></article>; })}
    </div>
  </div>;
}
