import 'package:flutter/material.dart';
import '../../models/jobseeker/jobseeker_models.dart';
import '../../services/api_client.dart';
import '../../services/jobseeker/jobseeker_service.dart';
import '../../theme/app_theme.dart';

class JobSeekerJobsScreen extends StatefulWidget {const JobSeekerJobsScreen({super.key,required this.service});final JobSeekerService service;@override State<JobSeekerJobsScreen> createState()=>_State();}
class _State extends State<JobSeekerJobsScreen>{List<JobSeekerJob> jobs=[];bool loading=true;String? error;String query='';
@override void initState(){super.initState();_load();}
Future<void> _load()async{setState(()=>loading=true);try{final x=await widget.service.getJobs();if(mounted)setState((){jobs=x;error=null;});}on ApiException catch(e){if(mounted)setState(()=>error=e.message);}finally{if(mounted)setState(()=>loading=false);}}
@override Widget build(BuildContext c){final shown=jobs.where((j)=>('${j.title} ${j.company} ${j.location} ${j.requiredSkills.join(' ')}').toLowerCase().contains(query.toLowerCase())).toList();return Column(children:[Padding(padding:const EdgeInsets.fromLTRB(16,16,16,8),child:TextField(onChanged:(v)=>setState(()=>query=v),decoration:const InputDecoration(prefixIcon:Icon(Icons.search_rounded),hintText:'Search jobs, companies, skills...'))),Expanded(child:loading?const Center(child:CircularProgressIndicator()):error!=null?_Err(error!,_load):shown.isEmpty?const Center(child:Text('No jobs found.')):RefreshIndicator(onRefresh:_load,child:ListView.separated(padding:const EdgeInsets.all(16),itemCount:shown.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(_,i){final j=shown[i];return Card(child:ListTile(contentPadding:const EdgeInsets.all(14),title:Text(j.title,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Padding(padding:const EdgeInsets.only(top:8),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('${j.company} • ${j.location}'),const SizedBox(height:6),Text('${j.workMode} • ${j.employmentType}',style:const TextStyle(color:AppTheme.muted)),if(j.requiredSkills.isNotEmpty)Padding(padding:const EdgeInsets.only(top:8),child:Wrap(spacing:6,children:j.requiredSkills.take(3).map((s)=>Chip(label:Text(s),visualDensity:VisualDensity.compact)).toList()))])),trailing:const Icon(Icons.chevron_right_rounded),onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>JobSeekerJobDetailScreen(job:j,service:widget.service))));}))) ]);}}
class JobSeekerJobDetailScreen extends StatefulWidget{const JobSeekerJobDetailScreen({super.key,required this.job,required this.service});final JobSeekerJob job;final JobSeekerService service;@override State<JobSeekerJobDetailScreen> createState()=>_Detail();}
class _Detail extends State<JobSeekerJobDetailScreen>{bool applying=false;Future<void> _apply()async{setState(()=>applying=true);try{await widget.service.apply(widget.job.id);if(!mounted)return;ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Application submitted successfully.')));}on ApiException catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.message)));}finally{if(mounted)setState(()=>applying=false);}}
@override Widget build(BuildContext c){final j=widget.job;return Scaffold(appBar:AppBar(title:const Text('Job details')),body:ListView(padding:const EdgeInsets.all(18),children:[Text(j.title,style:Theme.of(c).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w900)),const SizedBox(height:6),Text('${j.company} • ${j.location}',style:const TextStyle(color:AppTheme.muted)),const SizedBox(height:14),Wrap(spacing:8,runSpacing:8,children:[Chip(label:Text(j.workMode)),Chip(label:Text(j.employmentType)),Chip(label:Text(j.experienceLevel)),Chip(label:Text(j.salaryLabel))]),_Section('Description',j.description),_Section('Responsibilities',j.responsibilities),_Section('Requirements',j.requirements),if(j.requiredSkills.isNotEmpty)...[const SizedBox(height:12),const Text('Required skills',style:TextStyle(fontWeight:FontWeight.w800,fontSize:16)),const SizedBox(height:8),Wrap(spacing:8,runSpacing:8,children:j.requiredSkills.map((s)=>Chip(label:Text(s))).toList())],const SizedBox(height:22),FilledButton.icon(onPressed:applying?null:_apply,icon:applying?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.send_rounded),label:Text(applying?'Applying...':'Apply now'))]));}}
class _Section extends StatelessWidget{const _Section(this.title,this.body);final String title,body;@override Widget build(BuildContext c)=>body.trim().isEmpty?const SizedBox.shrink():Padding(padding:const EdgeInsets.only(top:18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:16)),const SizedBox(height:7),Text(body,style:const TextStyle(height:1.5))]));}
class _Err extends StatelessWidget{const _Err(this.m,this.retry);final String m;final VoidCallback retry;@override Widget build(BuildContext c)=>Center(child:Column(mainAxisSize:MainAxisSize.min,children:[Padding(padding:const EdgeInsets.all(20),child:Text(m,textAlign:TextAlign.center)),FilledButton(onPressed:retry,child:const Text('Retry'))]));}
